#import "../template/lab.typ": *
#import "../template/components.typ": *

// ============================================================================
// EduFramework Laboratory Series
// Lab 15 - Motor Speed Measurement
// English version
// ============================================================================


// ============================================================================
// 0. REFERENCES
// ============================================================================

#let refs = (
  (
    key: "umich-eecs461",
    type: "web",
    author: [University of Michigan],
    title: [EECS 461 - Embedded Control Systems],
    source: [Department of Electrical Engineering and Computer Science],
    url: "https://ece.engin.umich.edu/academics/course-information/course-descriptions/eecs-461/",
  ),

  (
    key: "tue-optical-encoder",
    type: "web",
    author: [Eindhoven University of Technology],
    title: [Incremental Optical Encoder and Position Measurement],
    source: [Technical Publication],
    url: "https://research.tue.nl/files/4381008/626579.pdf",
  ),

  (
    key: "ni-encoder",
    type: "web",
    author: [National Instruments],
    title: [Hardware Encoder Measurements: How-To Guide],
    source: [NI Technical Documentation],
    url: "https://knowledge.ni.com/KnowledgeArticleDetails?id=kA03q000000x1riCAA",
  ),

  (
    key: "ti-eqep-speed",
    type: "web",
    author: [Texas Instruments],
    title: [eQEP Position and Speed Measurement],
    source: [MCU+ SDK Documentation],
    url: "https://software-dl.ti.com/mcu-plus-sdk/esd/AM263X/08_05_00_24/exports/docs/api_guide_am263x/EXAMPLES_DRIVERS_EQEP_POSITION_SPEED.html",
  ),

  (
    key: "rockwell-encoder",
    type: "manual",
    author: [Rockwell Automation],
    title: [Encoder/Counter Modules User Manual],
    source: [Industrial Automation Documentation],
    url: "https://literature.rockwellautomation.com/idc/groups/literature/documents/um/1734-um006_-en-p.pdf",
  ),

  (
    key: "encoder-technologies",
    type: "web",
    author: [CUI Devices],
    title: [Capacitive, Magnetic, and Optical Encoders: Comparing the Technologies],
    source: [Technical Article],
    url: "https://www.arrow.com/en/resources/articles/2021/10/capacitive-magnetic-and-optical-encoders-comparing-the-technologies.html",
  ),

  (
    key: "maazedu-guide",
    type: "manual",
    author: [MaaZEDU],
    title: [MaaZEDU Development Board Guide],
    revision: [1.0],
    year: [2025],
  ),

  (
    key: "eduframework-encoder",
    type: "web",
    author: [EduFramework],
    title: [Encoder Device API],
    source: [EduFramework Source Code],
    url: "https://github.com/QuangTM15/s32k144-edu-framework",
  ),
)


// ============================================================================
// DOCUMENT WRAPPER
// ============================================================================

#show: lab.with(
  number: 15,
  language: "en",
  title: [Motor Speed Measurement],
  subtitle: [RPM Measurement with a Two-Channel Encoder Using EduFramework],
)


// ============================================================================
// 1. INTRODUCTION
// ============================================================================

= Introduction

== Lab Overview

Lab 14 used a motor driver module to configure the PWM level, direction, and
stop state of a DC motor. However, the PWM value represents only the control
command generated by the microcontroller and does not directly indicate the
actual mechanical speed of the motor.

In systems that require motion observation, an encoder can be used to provide
feedback from a rotating shaft. By counting encoder state transitions during a
defined time interval, the program can calculate rotational speed in
revolutions per minute (RPM). A two-channel encoder can also determine the
rotation direction from the phase relationship between the two signals
#cite-ref(refs, "ni-encoder") #cite-ref(refs, "rockwell-encoder").

This lab adds a two-channel A/B encoder to the motor system introduced in
Lab 14. The motor is driven continuously at a fixed PWM level, while
EduFramework measures the encoder signals and sends the actual RPM value to the
Serial Monitor through `Serial1`.

== Objectives

#objectives(
  items: (
    [
      Describe the role of an encoder in measuring rotational motion of a
      motor.
    ],

    [
      Explain the basic operating principle of a two-channel incremental A/B
      encoder and quadrature x4 decoding.
    ],

    [
      Determine the number of counts per revolution from the encoder pulse
      specification.
    ],

    [
      Use the Encoder Device API to update and read the motor RPM.
    ],

    [
      Display the motor speed in real time on the Serial Monitor.
    ],
  ),
)


// ============================================================================
// 2. BACKGROUND
// ============================================================================

= Background

== Encoder in Motion Measurement Systems

An encoder is a device that generates electrical signals corresponding to
mechanical motion. In rotating systems, an encoder is commonly attached to a
motor shaft to provide information about position, motion count, direction, or
speed #cite-ref(refs, "umich-eecs461") #cite-ref(refs, "rockwell-encoder").

Encoders can use different sensing principles. Common technologies include
optical, magnetic, and capacitive encoders
#cite-ref(refs, "encoder-technologies"). This lab uses an optical encoder
integrated directly with the DC motor.

In an optical encoder, a disk containing periodic slots or patterns rotates with
the motor shaft. A light source and optical receiver convert the variation in
light into a sequence of electrical pulses. A two-channel arrangement allows
the system to determine not only motion count but also the direction of
rotation #cite-ref(refs, "tue-optical-encoder").

== Two-Channel Incremental A/B Encoder

The encoder used in this lab provides two channels, A and B. These signals are
periodic and phase-shifted relative to each other. The order in which A and B
change depends on the direction of rotation, allowing the decoder to determine
motion in both directions #cite-ref(refs, "ni-encoder").

The channel states can be visualized as logic pairs:

`00` → `01` → `11` → `10` → `00`

When the rotation direction reverses, the transition order also reverses.
EduFramework tracks valid state transitions and increments or decrements the
encoder count accordingly #cite-ref(refs, "eduframework-encoder").

== Quadrature x4 Decoding and CPR

A complete cycle of a two-channel encoder contains four edge transitions that
can be counted. When both rising and falling edges of channels A and B are used,
the method is referred to as quadrature x4 decoding
#cite-ref(refs, "ni-encoder").

The encoder integrated with the motor used in this lab produces `30` pulses per
revolution. EduFramework uses x4 decoding, so the number of counts per
mechanical revolution is:

$ 30 times 4 = 120 $

Therefore, the `countsPerRevolution` value passed to `Encoder_Init()` is
`120U`.

#note[
  The CPR value passed to the Encoder Device API must represent the number of
  decoded counts per mechanical revolution, not only the nominal number of
  encoder pulses.
]

== RPM Calculation

Rotational speed can be calculated from the number of counts that change during
a defined time interval. The general principle is to measure the count change
within a sampling window, then convert the result using CPR and the elapsed time
to obtain revolutions per minute #cite-ref(refs, "ti-eqep-speed").

In EduFramework, the calculation can be represented by the following
relationship:

`RPM = |ΔCount| × 60000 / (CPR × Δt_ms)`

where:

- `ΔCount` is the count change during the measurement window;
- `CPR` is the number of counts per revolution;
- `Δt_ms` is the measurement-window duration in milliseconds;
- `60000` is the number of milliseconds in one minute.

RPM is returned as a positive magnitude. Rotation direction is managed
separately by the Encoder Device API.


// ============================================================================
// 3. HARDWARE SETUP
// ============================================================================

= Hardware Setup

== Required Hardware

Lab 15 continues to use the motor-control system from Lab 14 and adds the
encoder integrated with the motor. The TB6612FNG module and external power
supply continue to provide the motor power-control stage.

#hardware-table(
  caption: [Hardware used in this lab],

  rows: (
    (
      [MaaZEDU Development Board],
      [Development board based on the S32K144 microcontroller.],
    ),

    (
      [TB6612FNG Motor Driver Module],
      [Motor driver module previously used in Lab 14.],
    ),

    (
      [DC Motor with Encoder],
      [
        DC motor with an integrated two-channel A/B optical encoder,
        30 pulses per revolution.
      ],
    ),

    (
      [External Motor Power Supply],
      [External supply that powers the motor through the TB6612FNG.],
    ),

    (
      [Jumper wires],
      [Connect the control, encoder, and power signals.],
    ),

    (
      [USB Cable],
      [
        Connects MaaZEDU to the computer for program uploading and Serial
        Monitor communication.
      ],
    ),
  ),
)

== Motor Control Connections

The motor-control connections remain unchanged from Lab 14:

#pin-table(
  caption: [Motor-control signals reused from Lab 14],

  rows: (
    (
      [TB6612FNG PWMA],
      "GPIO2",
      "PTD14",
      [PWM Output],
    ),

    (
      [TB6612FNG AIN1],
      "GPIO3",
      "PTD13",
      [Digital Output],
    ),

    (
      [TB6612FNG AIN2],
      "GPIO4",
      "PTD12",
      [Digital Output],
    ),

    (
      [TB6612FNG STBY],
      "GPIO5",
      "PTD11",
      [Digital Output],
    ),
  ),
)

The H-bridge, `VCC` supply, `VM` supply, and PWM-control details were covered in
Lab 14 and are therefore not repeated in this lab.

== Motor and Encoder Connections

The motor used in this lab has a six-pin connector. According to the verified
hardware configuration, the pins are connected as follows:

#block(
  width: 100%,
  breakable: false,
)[
  #table(
    columns: (1fr, 1.5fr, 2.2fr),
    align: (center + horizon, center + horizon, left + horizon),
    stroke: 0.4pt + table-line,
    inset: 7pt,

    table.header(
      repeat: true,

      table.cell(fill: table-header-gray)[
        #align(center + horizon)[*Motor Pin*]
      ],

      table.cell(fill: table-header-gray)[
        #align(center + horizon)[*Connection*]
      ],

      table.cell(fill: table-header-gray)[
        #align(center + horizon)[*Function*]
      ],
    ),

    [Pin 1], [`AO1`], [First motor terminal.],
    [Pin 2], [`AO2`], [Second motor terminal.],
    [Pin 3], [`3.3V`], [Encoder power supply.],
    [Pin 4], [`GND`], [Encoder ground.],
    [Pin 5], [`GPIO8`], [Encoder Channel A.],
    [Pin 6], [`GPIO9`], [Encoder Channel B.],
  )
]

`GPIO8` and `GPIO9` are selected as the two encoder inputs because these
Logical Pins support Digital Input and external interrupt capability in the
current EduFramework configuration #cite-ref(refs, "maazedu-guide")
#cite-ref(refs, "eduframework-encoder").

== Connection Diagram

#figure-block(
  caption: [Connection diagram for the DC motor with integrated encoder and MaaZEDU],
)[
  #image(
    "../assets/circuits/motor_encoder.png",
    width: 100%,
  )
]


// ============================================================================
// 4. EDUFRAMEWORK API
// ============================================================================

= EduFramework API

Lab 15 reuses the DC Motor Device API from Lab 14 to create motion and focuses
on the new Encoder Device API. The main APIs used in the exercise are
`Encoder_Init()`, `Encoder_Reset()`, `Encoder_Update()`, and `Encoder_GetRpm()`
#cite-ref(refs, "eduframework-encoder").

== `Encoder_Init()`

`Encoder_Init()` initializes the two encoder channels and configures the number
of counts per revolution.

#api-detail(
  name: "Encoder_Init",

  syntax: [Encoder_Init(channelAPin, channelBPin, countsPerRevolution);],

  description: [
    Initialize a two-channel encoder and configure the number of decoded counts
    per mechanical revolution.
  ],

  parameters: (
    (
      [channelAPin],
      [Logical Pin],
      [Pin connected to encoder Channel A.],
    ),

    (
      [channelBPin],
      [Logical Pin],
      [Pin connected to encoder Channel B.],
    ),

    (
      [countsPerRevolution],
      [Count / revolution],
      [Number of decoded counts per mechanical revolution.],
    ),
  ),

  returns: [
    Returns `1U` when initialization is successful and `0U` when the
    configuration is invalid.
  ],
)

Example:

```c
Encoder_Init(GPIO8, GPIO9, 120U);
```

== `Encoder_Reset()`

`Encoder_Reset()` resets the accumulated count, RPM value, and rotation
direction state to their initial values.

#api-detail(
  name: "Encoder_Reset",

  syntax: [Encoder_Reset();],

  description: [
    Reset the encoder measurement state.
  ],

  parameters: (),

  returns: [No return value.],
)

== `Encoder_Update()`

`Encoder_Update()` updates the speed measurement using the encoder count and
elapsed time. The function is non-blocking and should be called repeatedly from
the main loop.

#api-detail(
  name: "Encoder_Update",

  syntax: [Encoder_Update();],

  description: [
    Update the latest encoder RPM and rotation direction.
  ],

  parameters: (),

  returns: [No return value.],
)

In the current EduFramework version, RPM is updated using an internal
measurement window. The application can continue performing other tasks between
updates.

== `Encoder_GetRpm()`

`Encoder_GetRpm()` returns the latest rotational speed calculated by
`Encoder_Update()`.

#api-detail(
  name: "Encoder_GetRpm",

  syntax: [Encoder_GetRpm();],

  description: [
    Read the latest encoder rotational speed.
  ],

  parameters: (),

  returns: [Rotational speed in revolutions per minute (RPM).],
)

EduFramework also provides `Encoder_GetCount()` and `Encoder_GetDirection()` to
read the accumulated count and rotation direction. These APIs are not required
in the main exercise but can be used when additional encoder state information
is needed.


// ============================================================================
// 5. LAB EXERCISE
// ============================================================================

= Lab Exercise

== Requirements

Build a program that runs the motor continuously at approximately `50%` control
level, measures the speed using the encoder, and displays the RPM on the Serial
Monitor.

The program must meet the following requirements:

- Initialize Serial1 at `9600 bps`.
- Initialize the motor-control system using `GPIO2` through `GPIO5`.
- Initialize the encoder with Channel A on `GPIO8`, Channel B on `GPIO9`, and
  `120` counts per revolution.
- Set the motor speed-control value to `128`.
- Run the motor continuously in the Forward direction.
- Call `Encoder_Update()` continuously in the main loop.
- Display the RPM on the Serial Monitor every `200 ms`.

== Program

In `src/main.c`, implement the program as follows:

#block(breakable: false)[
  #code-listing(
    caption: [Motor speed measurement program using an encoder],
  )[
    ```c
    #include "Arduino.h"
    #include "hardware_serial.h"
    #include "dc_motor.h"
    #include "encoder.h"

    int main(void)
    {
        uint32_t previousTime = 0U;

        setup();

        Serial1_begin(9600U);

        DCMotor_Init(GPIO2, GPIO3, GPIO4, GPIO5);

        if (0U == Encoder_Init(GPIO8, GPIO9, 120U))
        {
            Serial1_println("Encoder initialization failed.");

            while (1)
            {
            }
        }

        Encoder_Reset();

        DCMotor_SetSpeed(128U);
        DCMotor_Forward();

        Serial1_println("Motor speed measurement started.");

        while (1)
        {
            Encoder_Update();

            if ((millis() - previousTime) >= 200U)
            {
                previousTime = millis();

                Serial1_print("RPM: ");
                Serial1_printFloat(Encoder_GetRpm());
                Serial1_println("");
            }
        }

        return 0;
    }
    ```
  ]
]

== Program Explanation

After `setup()`, `Serial1_begin(9600U)` initializes the Serial Monitor. The motor
control section continues to use the configuration introduced in Lab 14.

`Encoder_Init(GPIO8, GPIO9, 120U)` configures the two encoder channels and
declares `120` counts per revolution. If initialization fails, the program
prints an error message and does not continue to the measurement stage.

After `Encoder_Reset()` resets the measurement state,
`DCMotor_SetSpeed(128U)` sets the control level to approximately `50%`, and
`DCMotor_Forward()` keeps the motor rotating continuously.

Inside the main loop, `Encoder_Update()` is called continuously to update the
speed measurement. Every `200 ms`, the program reads the latest value using
`Encoder_GetRpm()` and sends the result to the Serial Monitor.

Separating the Serial update timing from the encoder measurement allows the
main loop to continue calling `Encoder_Update()` frequently instead of blocking
the program with `delay()`.

== Verification

Build and upload the program to the MaaZEDU Development Board. Apply external
power to the motor, open the Serial Monitor at `9600 bps`, and observe the
output.

Example:

```text
Motor speed measurement started.
RPM: 2115.000
RPM: 2130.000
RPM: 2125.000
RPM: 2130.000
```

The actual RPM depends on the motor, supply voltage, mechanical load, and
operating conditions, so it is not required to match the example exactly.

#expected-result[
  The motor rotates continuously in one direction at control value `128`. The
  Serial Monitor displays the RPM measured by the encoder and updates the value
  periodically at approximately `200 ms`. When the motor speed becomes stable,
  consecutive RPM values fluctuate around a relatively stable level.
]


// ============================================================================
// 6. EXTENSION
// ============================================================================

= Extension

The main exercise uses a fixed PWM level to focus on encoder-based speed
measurement. By combining UART input data with RPM feedback, the program can be
extended into an interactive motor-speed control application.

== Adjusting the PWM Level through UART

Extend the program so that the user can enter a value from `0` to `255` through
the Serial Monitor. The received value is used as the new control level for
`DCMotor_SetSpeed()`.

After each change in the control value, the encoder continues to measure the
actual speed and the Serial Monitor displays the corresponding RPM.

The intended processing flow is:

`UART Input` → `PWM Command` → `DC Motor` → `Encoder` → `Measured RPM`

*Hints:*

- Check incoming data from `Serial1`.
- Convert the received data into a numeric value.
- Verify that the value is within the `0..255` range.
- Update the control level using `DCMotor_SetSpeed()`.
- Continue calling `Encoder_Update()` in the main loop.
- Display both the current PWM value and the actual RPM for comparison.

An automatic algorithm that adjusts PWM according to RPM is not required. The
user directly changes the control command and observes the measured motor-speed
response.

#expected-result[
  The user can enter different control levels through the Serial Monitor. The
  motor speed changes accordingly, and the encoder provides the actual RPM so
  that the effect of each PWM level can be observed.
]


// ============================================================================
// 7. REFERENCES
// ============================================================================

= References

#references(refs)
